"""Dovie-facing Hermes Gateway capability contract."""

from __future__ import annotations

import importlib.util
from typing import Any

CONTRACT_VERSION = "2026-07-12"
EXTENSION_VERSION = "2026-07-12"

REQUIRED_METHODS = [
    "gateway.capabilities",
    "session.create",
    "session.list",
    "session.messages",
    "session.message_metadata.merge",
    "session.branch",
    "session.status",
    "session.usage",
    "activity.list",
    "activity.get",
    "activity.cancel",
    "activity.mark_read",
    # ADR-0001 §Phase 1.B Activity Command bus entrypoints + §Phase 2.A/2.E-1
    # activity-scoped subscription and maintenance RPCs. Replace the legacy
    # team_mission.subscribe (removed §Phase 2.E-5).
    "activity.create",
    "activity.start",
    "activity.complete",
    "activity.command.cancel",
    "runtime.activity.subscribe",
    "runtime.activity.unsubscribe",
    "runtime.activity.maintenance",
    "conversation.activity.list",
    "conversation.activity.context.change",
    "conversation.render_snapshot",
    "session.delete",
    "session.title",
    "prompt.submit",
    "run.reserve",
    "run.retry.prepare",
    "run.submit",
    "run.cancel",
    "run.status",
    "run.events",
    "events.subscribe",
    "events.unsubscribe",
    "team_mission.create",
    "team_registry.team.upsert",
    "team_registry.team.get",
    "team_registry.team.list",
    "team_registry.team.archive",
    "team_registry.member.upsert",
    "team_registry.member.get",
    "team_registry.member.list",
    "team_registry.member.delete",
    "profile.upsert",
    "profile.get",
    "profile.growth.summary",
    "profile.learning.graph",
    "profile.learning.node.detail",
    "profile.learning.node.edit",
    "profile.learning.node.delete",
    "profile.list",
    "profile.archive",
    "profile.draft.upsert",
    "profile.draft.get",
    "profile.draft.list",
    "profile.draft.discard",
    "team_mission.graph",
    "team_mission.graph.reduce",
    "team_mission.snapshot.get",
    "team_mission.result.get",
    "team_mission.events",
    "team_capability.snapshot.get",
    "team_capability.snapshot.refresh",
    "team_capability.snapshot.bind",
    "team_mission.team_profile.get",
    "team_mission.conversation.ensure",
    "team_mission.conversation.resolve",
    "team_mission.conversation.render",
    "team_mission.conversation.list",
    "team_mission.conversation.participants",
    "team_mission.conversation.execution_session_ids",
    "team_mission.conversation.rename",
    "team_mission.conversation.delete",
    "team_mission.message.submit",
    "team_mission.cancel",
    "team_mission.node.create",
    "team_mission.edge.create",
    "team_mission.node.update",
    "team_mission.node.bind_run",
    "team_mission.node.history",
    "team_mission.node.start",
    "team_mission.plan.complete",
    "team_mission.plan.approve",
    "team_mission.schedule.ready",
    "conversation.memory.propose",
    "conversation.memory.commit",
    "conversation.memory.invalidate",
    "conversation.memory.list",
    "conversation.context.summary.list",
    "model.set",
    "model.options",
    "approval.pending.list",
    "approval.policy.get",
    "approval.policy.set",
    "approval.respond",
    "sudo.respond",
    "secret.respond",
    "clarify.respond",
    "cron.manage",
    "skills.manage",
    "toolsets.list",
    "profile.prepare_runtime",
    "profile.runtime.session_exists",
    "runtime.ensure",
    "runtime.status",
    "runtime.state.inspect",
    "runtime.state.prune_empty",
    "runtime.state.merge_profile_runtime",
    "storage.stats",
    "team_mission.workspace.rebase_paths",
    "workspace.current",
    "workspace.session.current",
    "workspace.session.bind",
    "workspace.session.list",
    "workspace.session.delete",
    "workspace.list",
    "artifacts.list",
    "artifacts.register",
    "artifacts.delete",
]

REQUIRED_EVENTS = [
    "message.delta",
    "message.complete",
    "reasoning.delta",
    "reasoning.available",
    "tool.generating",
    "tool.start",
    "tool.progress",
    "tool.complete",
    "approval.request",
    "sudo.request",
    "secret.request",
    "clarify.request",
    "artifact.created",
    "artifact.deleted",
    "subagent.output_delta",
    "subagent.reasoning_delta",
    "agent_profile_test.start",
    "agent_profile_test.output_delta",
    "agent_profile_test.thinking",
    "agent_profile_test.tool",
    "agent_profile_test.progress",
    "agent_profile_test.complete",
]

REQUIRED_STATE_FEATURES = [
    "state:runtime_scope_key",
    "state:transient_session",
    "state:run_registry",
    "state:run_event_log",
    "state:agent_profile_registry",
    "state:team_mission_graph",
    "state:team_mission_snapshot",
    "state:team_mission_result",
    "state:team_registry",
    "state:team_mission_conversation",
    "state:conversation_memory",
    "state:team_capability_snapshot",
    "state:message_reasoning",
    "state:session_search",
]

REQUIRED_RUNTIME_FEATURES = [
    "runtime:control_plane",
    "runtime:dovie_sidecar",
    "runtime:profile_scope",
    "runtime:cloud_proxy_auth",
]

SUPPORTED_STATE_FEATURES = frozenset(REQUIRED_STATE_FEATURES)

REQUIRED_GATEWAY_METHODS = {
    "gateway.capabilities",
    "session.create",
    "session.list",
    "session.messages",
    "session.close",
    "session.index.list",
    "session.recall_turn",
    "session.events",
    "run.fail",
    "events.compact",
    "subagent.runs.list",
    "subagent.events.list",
    "skills.list",
    "skills.reload",
    "tools.prepare",
    "tools.configure",
    "storage.maintenance.run",
    "storage.maintenance.status",
    "session.message_metadata.merge",
    "session.branch",
    "session.status",
    "session.usage",
    "project.facts",
    "verification.status",
    "activity.list",
    "activity.get",
    "activity.cancel",
    "activity.mark_read",
    "activity.create",
    "activity.start",
    "activity.complete",
    "activity.command.cancel",
    "runtime.activity.subscribe",
    "runtime.activity.unsubscribe",
    "runtime.activity.maintenance",
    "runtime.cloud_proxy.update",
    "conversation.activity.list",
    "conversation.activity.context.change",
    "conversation.render_snapshot",
    "session.delete",
    "session.title",
    "run.reserve",
    "run.retry.prepare",
    "run.submit",
    "run.cancel",
    "run.status",
    "run.events",
    "events.subscribe",
    "events.unsubscribe",
    "team_mission.create",
    "team_registry.team.upsert",
    "team_registry.team.get",
    "team_registry.team.list",
    "team_registry.team.archive",
    "team_registry.member.upsert",
    "team_registry.member.get",
    "team_registry.member.list",
    "team_registry.member.delete",
    "profile.upsert",
    "profile.get",
    "profile.growth.summary",
    "profile.learning.graph",
    "profile.learning.node.detail",
    "profile.learning.node.edit",
    "profile.learning.node.delete",
    "profile.list",
    "profile.archive",
    "profile.draft.upsert",
    "profile.draft.get",
    "profile.draft.list",
    "profile.draft.discard",
    "team_mission.graph",
    "team_mission.conversation.recall_turn",
    "team_mission.plan.reject",
    "team_mission.graph.reduce",
    "team_mission.snapshot.get",
    "team_mission.result.get",
    "team_mission.events",
    "team_capability.snapshot.get",
    "team_capability.snapshot.refresh",
    "team_capability.snapshot.bind",
    "team_mission.team_profile.get",
    "team_mission.conversation.ensure",
    "team_mission.conversation.resolve",
    "team_mission.conversation.render",
    "team_mission.conversation.list",
    "team_mission.conversation.participants",
    "team_mission.conversation.execution_session_ids",
    "team_mission.conversation.rename",
    "team_mission.conversation.delete",
    "team_mission.message.submit",
    "team_mission.cancel",
    "team_mission.node.create",
    "team_mission.edge.create",
    "team_mission.node.update",
    "team_mission.node.bind_run",
    "team_mission.node.history",
    "team_mission.node.start",
    "team_mission.plan.complete",
    "team_mission.plan.approve",
    "team_mission.schedule.ready",
    "conversation.memory.propose",
    "conversation.memory.commit",
    "conversation.memory.invalidate",
    "conversation.memory.list",
    "conversation.context.summary.list",
    "model.set",
    "model.options",
    "approval.pending.list",
    "approval.policy.get",
    "approval.policy.set",
    "approval.respond",
    "sudo.respond",
    "secret.respond",
    "clarify.respond",
    "cron.manage",
    "skills.manage",
    "toolsets.list",
    "profile.prepare_runtime",
    "profile.runtime.session_exists",
    "runtime.ensure",
    "runtime.status",
    "runtime.state.inspect",
    "runtime.state.prune_empty",
    "runtime.state.merge_profile_runtime",
    "codex.auth.status",
    "codex.auth.login.start",
    "codex.auth.login.poll",
    "codex.auth.logout",
    "codex.auth.import_cli",
    "storage.stats",
    "team_mission.workspace.rebase_paths",
    "workspace.current",
    "workspace.session.current",
    "workspace.session.bind",
    "workspace.session.list",
    "workspace.session.delete",
    "workspace.list",
    "artifacts.list",
    "artifacts.register",
    "artifacts.delete",
    "prompt.submit",
}


def _module_exists(name: str) -> bool:
    try:
        return importlib.util.find_spec(name) is not None
    except Exception:
        return False


def _gateway_methods_present() -> set[str]:
    return set(REQUIRED_GATEWAY_METHODS)


def _state_features_present() -> set[str]:
    return set(SUPPORTED_STATE_FEATURES)


def _runtime_features_present() -> set[str]:
    present = set()
    if _module_exists("tui_gateway.dovie_sidecar"):
        present.add("runtime:dovie_sidecar")
        present.add("runtime:control_plane")
    if _module_exists("tui_gateway.services.runtime_pool"):
        present.add("runtime:profile_scope")
    if "runtime:dovie_sidecar" in present:
        present.add("runtime:cloud_proxy_auth")
    return present


def gateway_capabilities() -> dict[str, Any]:
    from tui_gateway.services.contract_capabilities import timeline_contract_capabilities

    methods = sorted(_gateway_methods_present())
    state_features = sorted(_state_features_present())
    runtime_features = sorted(_runtime_features_present())

    missing_methods = sorted(set(REQUIRED_METHODS) - set(methods))
    missing_events: list[str] = []
    missing_state_features = sorted(set(REQUIRED_STATE_FEATURES) - set(state_features))
    missing_runtime_features = sorted(set(REQUIRED_RUNTIME_FEATURES) - set(runtime_features))
    missing_capabilities = sorted(
        set(missing_methods)
        | set(missing_events)
        | set(missing_state_features)
        | set(missing_runtime_features)
    )
    return {
        "protocolVersion": CONTRACT_VERSION,
        "hermesVersion": "",
        "extensionVersion": EXTENSION_VERSION,
        "methods": methods,
        "events": list(REQUIRED_EVENTS),
        "stateFeatures": state_features,
        "runtimeFeatures": runtime_features,
        "missingMethods": missing_methods,
        "missingEvents": missing_events,
        "missingStateFeatures": missing_state_features,
        "missingRuntimeFeatures": missing_runtime_features,
        "missingCapabilities": missing_capabilities,
        "timelineContract": timeline_contract_capabilities(),
        "ok": not missing_capabilities,
    }
